### PR TITLE
Move past events from /<year> to /events/<year>

### PR DESCRIPTION
**Pull request by rockmanvnx6**
Didn't quite notice the dependencies but this should work. We don't have a `/events` page yet.

### CODE REVIEW

**Comment by terencehuynh** [comment]
Based on the preview, looks good. The only thing is that the "More from UNIHACK 2021" button on the home page doesn't work any more.

You'll need to change it to point to /events/2021 - and that link can be found in the BrandHero component.

**Review by terencehuynh — CHANGES_REQUESTED** [review]
LGTM, but the "More from UNIHACK 2021" button on the home page is not working.

**Comment by rockmanvnx6** [comment]
Sorry I missed that. Thanks for pointing out. Should work now.

**Review by terencehuynh — APPROVED** [review]
Thanks for that, LGTM!

**Comment by terencehuynh** [comment]
@all-contributors please add @rockmanvnx6 for code

**Pull request merged**
